export const FETCH_PRODUCT = "FETCH_PRODUCT"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const FETCH_PRODUCT_REQ = "FETCH_PRODUCT_REQ"

export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS"

export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE"

export const ADD_TO_CART = "ADD_TO_CART"